name: Run Unit Test Suites

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go Environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.19.2'
      - name: run unit test cases 
        working-directory: ./
        run: |
          make test
